#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-bluetooth
show_usage () {
    echo "usage: $SCRIPTNAME [-a action]"
    echo "Get Bluetooth functionality."
    echo "  -a action  action available [status/pair/send] "
    exit 0
}

validate_action () {
    ACTION=$1
    case "$ACTION" in
        status) ;;
        pair) ;;
        send) ;;
        *) echo "$SCRIPTNAME: Unsupported action: '$ACTION'"; exit 1;;
    esac
}


PARAMS=""

while getopts :hr:p: option
do
    case "$option" in
        h) show_usage;;
        a) validate_provider $OPTARG; PARAMS="$PARAMS --es provider $OPTARG";;
        ?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $(($OPTIND-1))

if [ $# != 0 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi

/data/data/com.termux/files/usr/libexec/termux-api Bluetooth $PARAMS
